# Rule Configuration
rules:
  indentation:
    - 1
    -
      size: 4
  class-name-format: 0
  no-css-comments: 0
  nesting-depth: 0
  no-transition-all: 0
  no-color-literals: 0
  property-sort-order: 0
  empty-line-between-blocks: 0
  no-ids: 0
  no-qualifying-elements: 0
  force-attribute-nesting: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  mixins-before-declarations: 0
