imports:
    - { resource: ../config.yml }
    - { resource: ezplatform.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/dev/routing.yml'
        strict_requirements: true
    profiler:
        only_exceptions: false
        # Optional: Skips generating profiles for subrequests by default due to dev performance
        only_master_requests: true
    assets:
        packages:
            app:
                json_manifest_path: '%kernel.project_dir%/web/assets/app/build_dev/manifest.json'

webpack_encore:
    output_path: false
    builds:
        # The path where Encore is building the assets - i.e. Encore.setOutputPath()
        app: '%kernel.project_dir%/web/assets/app/build_dev'

snc_redis:
    clients:
        symfony_profiler:
            type: '%profiler_storage_driver%'
            alias: symfony_profiler
            dsn: 'redis://%profiler_storage_dsn%'
            options:
                prefix: '%profiler_storage_namespace%'

web_profiler:
    toolbar: true
    intercept_redirects: false
    # By default disable showing of Admin UI "notifications/count" in web debug toolbar AJAX calls list to make it more manageable.
    excluded_ajax_paths: '(^/(app(_[\\w]+)?\\.php/)?_wdt)|/notifications/count'

monolog:
    handlers:
        main:
            type: '%log_type%'
            path: '%log_path%'
            level: debug
            channels: ['!event', '!doctrine']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
