parameters:
    netgen_content_browser.ezplatform.item_template: '@@ezdesign/browser/item.html.twig'
    netgen_content_browser.ezplatform.preview_template: '@@ezdesign/browser/ngcb_preview.html.twig'
