parameters:
    ngsite.default.search.content_types:
        - ng_blog_post
        - ng_article
        - ng_news
        - ng_category
        - ng_feedback_form
        - ng_landing_page
        - ng_video
        - ng_audio
        - file

    netgen_admin_ui.default.legacy_routes: [ez_urlalias, ngsite_content_search]

    ngsite.default.lazy_loading.enabled: true
    ngsite.default.lazy_loading.initial_image_alias: 'i30'
    ngsite.default.render_content_directly: true

    app.default.weather.base_url: 'api.openweathermap.org/data/2.5/weather'
    app.default.weather.appid: 'd94fb9615f049314b63b84482d6ea8fd'
    app.default.weather.ttl: 1200
