parameters:

services:
    app.weather.config_resolver:
        class: AppBundle\Weather\OpenWeatherMapConfigResolver
        public: false
        arguments:
            - '@ezpublish.config.resolver'

    app.weather.client:
        class: AppBundle\Weather\OpenWeatherMapClient
        arguments:
            - '@app.weather.config_resolver'
            - '@httplug.client.default'
            - '@httplug.message_factory'

    app.weather.controller:
        class: AppBundle\Controller\WeatherController
        public: true
        arguments:
            - '@twig'
            - '@app.weather.client'

    app.weather.cache_controller:
        class: AppBundle\Controller\CacheClearController
        public: true
        arguments:
            - '@cache.app'
            - '@app.weather.key_registry'

    app.weather.key_registry:
        class: AppBundle\Weather\CacheKeyRegistry

    app.weather.psr6_client:
        class: AppBundle\Weather\Psr6DecoratedOpenWeatherMapClient
        decorates: app.weather.client
        decoration_inner_name: app.weather.client.inner
        public: false
        arguments:
            - '@app.weather.client.inner'
            - '@cache.app'
            - '@ezpublish.config.resolver'
            - '@app.weather.key_registry'
