parameters:
    ngsite.layouts.block.plugin.background_color.colors:
        primary: 'block.plugin.background_color.primary'
        secondary: 'block.plugin.background_color.secondary'
        white: 'block.plugin.background_color.white'
        black: 'block.plugin.background_color.black'

services:
